In [2]:
import numpy as np

random_vector = np.random.randint(1, 21, size=15)
reshaped_array = random_vector.reshape(3, 5)

for row in range(reshaped_array.shape[0]):
    max_value = np.max(reshaped_array[row])
    reshaped_array[row][reshaped_array[row] == max_value] = 0

print("Reshaped Array with Maximum in Each Row Replaced by 0:\n", reshaped_array)

new_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.int32)
print("\nNew 2D Array:\n", new_array)
print("Shape:", new_array.shape)
print("Type:", type(new_array))
print("Data Type:", new_array.dtype)

Reshaped Array with Maximum in Each Row Replaced by 0:
 [[14  8  0  0  5]
 [14 13 11  0  4]
 [ 1  1  0  8 15]]

New 2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data Type: int32


In [3]:
import numpy as np

A = np.array([[3, -2], [1, 0]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nRight Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[2. 1.]

Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]])

diagonal_sum = np.trace(arr)

print("Given Array:")
print(arr)

print("\nSum of Diagonal Elements:", diagonal_sum)

Given Array:
[[0 1 2]
 [3 4 5]]

Sum of Diagonal Elements: 4


In [5]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])
print("Original array:\n", arr)

arr_reshaped_2x3 = arr.reshape(2, 3)
print("\nReshaped to 2x3:\n", arr_reshaped_2x3)

arr_reshaped_3x2 = arr_reshaped_2x3.reshape(3, 2)
print("\nReshaped back to 3x2:\n", arr_reshaped_3x2)

Original array:
 [[1 2]
 [3 4]
 [5 6]]

Reshaped to 2x3:
 [[1 2 3]
 [4 5 6]]

Reshaped back to 3x2:
 [[1 2]
 [3 4]
 [5 6]]
